### ISSUE TITLE
Icon names containing ~ are not replaced

### ISSUE THREAD

**Issue by jc86035** [JJMC89/JJMC89_bot#28]
There are now redirects that contain single tildes. They are not being replaced because of `[^\\~\n]+?` in the regular expressions.

**Comment by jc86035** [comment]
It might be possible simply to remove ~ from that part of the regular expression. Even with icon names starting and ending with ~, the regular expression seems to work (and in some cases the tildes would have to be separated by a space anyway to prevent signature generation).

**Comment by JJMC89** [comment]
Taking [ru:Template:Малое кольцо Московской железной дороги](https://ru.wikipedia.org/wiki/%D0%A8%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD:%D0%9C%D0%B0%D0%BB%D0%BE%D0%B5_%D0%BA%D0%BE%D0%BB%D1%8C%D1%86%D0%BE_%D0%9C%D0%BE%D1%81%D0%BA%D0%BE%D0%B2%D1%81%D0%BA%D0%BE%D0%B9_%D0%B6%D0%B5%D0%BB%D0%B5%D0%B7%D0%BD%D0%BE%D0%B9_%D0%B4%D0%BE%D1%80%D0%BE%D0%B3%D0%B8) as a testcase, that change results in the following new regex matches (icon part only): `['~~', '~~1,2', '~~3,8', '~~4,9', '~~6,5', '~~13,8', '~~18,6', '~~20,3', '~~', '~~21,2', '~~', '~~', '~~', '~~25,5', "~~''{{ст.|Симоново}}'', ''{{ст.|Лизино}}''", '~~27,9', '~~30,2', '~~31,0', '~~33,4', '~~33,9', '~~35,0', '~~37,5', '~~37,9', 'exlv-BHF~g', '~~38,6', '~~39,3', 'exlvBST~g-', '~~', 'dBHF~R yellow', "~~''{{ст.|Октябрьские Казармы}}''", 'dBHF~R yellow', '~~44', '~~46,5', '~~', '~~48,0', '~~49,5']`. Since most of those don't represent BSicons, we are left with `['exlv-BHF~g', 'exlvBST~g-', 'dBHF~R yellow', 'dBHF~R yellow']` to check if they should be replaced.

@jc86035 Please confirm this is the desired change.

**Comment by jc86035** [comment]
I think this should be fine. BSicon names can't contain two consecutive tildes anyway (due to {{Routemap}} restrictions), although it might help to filter out matches containing two consecutive tildes to prevent indirect vandalism (e.g. from the creation of [[File:BSicon ~~.svg]] as a redirect).

**Comment by JJMC89** [comment]
`(?=((?:\n|! !|!~|\\)[ \t]*)((?:[^\\~\n]|~(?!~))+?)([ \t]*(?:\n|!~|~~|!@|__|!_|\\)))` should do it and gives `['exlv-BHF~g', 'exlvBST~g-', 'dBHF~R yellow', 'dBHF~R yellow']` as new icon matches for the testcase.

**Comment by jc86035** [comment]
@JJMC89 the icons are still not being replaced; e.g. [w:en:Template:Duckmanton Junction](https://en.wikipedia.org/w/index.php?title=Template:Duckmanton_Junction). Interestingly this still happens in BS-map diagrams where the regex shouldn't affect tildes at all; e.g. [w:en:Template:Dublin-Waterford railway line](https://en.wikipedia.org/wiki/Template:Dublin-Waterford_railway_line). I suspect this might be because the redirect list is not being downloaded due to being too long. Its length has tripled since 19 May. Maybe another mass deletion of unused redirects is needed.

**Comment by JJMC89** [comment]
> the icons are still not being replaced

That is unrelated to the code change here. See https://github.com/JJMC89/JJMC89_bot/issues/29#issuecomment-393929449.
